[openai]
# Substitua "sua-chave-api-aqui" pela sua chave de API da OpenAI
api_key = "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"
