[openai]
# Substitua "sua-chave-api-aqui" pela sua chave de API da OpenAI
api_key = "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"
